services:
  app:
    build: .
    ports:
      - "5159:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=130805
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130805
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/dumps/init.sql.gz:/tmp/init.sql.gz:ro
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: