// <auto-generated />
using System;
using BlazorApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp2.Models.Cam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeid");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cams", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.EquipmentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressIp")
                        .HasColumnType("text")
                        .HasColumnName("addressip");

                    b.Property<string>("Bu")
                        .HasColumnType("text")
                        .HasColumnName("bu");

                    b.Property<string>("Equipment")
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("EquipmentType")
                        .HasColumnType("text")
                        .HasColumnName("equipmenttype");

                    b.Property<string>("Fd")
                        .HasColumnType("text")
                        .HasColumnName("fd");

                    b.Property<string>("Gateway")
                        .HasColumnType("text")
                        .HasColumnName("gateway");

                    b.Property<string>("Mask")
                        .HasColumnType("text")
                        .HasColumnName("mask");

                    b.Property<string>("Network")
                        .HasColumnType("text")
                        .HasColumnName("network");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeid");

                    b.Property<int?>("Pvn")
                        .HasColumnType("integer")
                        .HasColumnName("pvn");

                    b.Property<string>("Rubezh")
                        .HasColumnType("text")
                        .HasColumnName("rubezh");

                    b.HasKey("Id");

                    b.ToTable("equipmentsummaries", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("createdat");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticketid");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FdIp")
                        .HasColumnType("text")
                        .HasColumnName("fdip");

                    b.Property<string>("Group")
                        .HasColumnType("text")
                        .HasColumnName("Group");

                    b.Property<bool?>("IgnoredInTask")
                        .HasColumnType("boolean")
                        .HasColumnName("ignoredintask");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("modelname");

                    b.Property<int?>("PvnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pvnnumber");

                    b.Property<string>("SerialFd")
                        .HasColumnType("text")
                        .HasColumnName("serialfd");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.NodeSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeid");

                    b.Property<string>("PlaceCode")
                        .HasColumnType("text")
                        .HasColumnName("placecode");

                    b.Property<string>("SchemeNumber")
                        .HasColumnType("text")
                        .HasColumnName("schemenumber");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("nodeschemas", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("AppStartedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("appstarted_at");

                    b.Property<bool?>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long?>("DisconnectedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("disconnected_at");

                    b.Property<int?>("Downtime")
                        .HasColumnType("integer")
                        .HasColumnName("downtime");

                    b.Property<string>("DowntimeHr")
                        .HasColumnType("text")
                        .HasColumnName("downtimehr");

                    b.Property<bool?>("Errors")
                        .HasColumnType("boolean")
                        .HasColumnName("errors");

                    b.Property<string>("ErrorsDescription")
                        .HasColumnType("text")
                        .HasColumnName("errors_description");

                    b.Property<string>("Group")
                        .HasColumnType("text")
                        .HasColumnName("Group");

                    b.Property<long?>("LastReportAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_report_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("node_id");

                    b.Property<long?>("PingAt")
                        .HasColumnType("bigint")
                        .HasColumnName("ping_at");

                    b.Property<string>("PvnNumber")
                        .HasColumnType("text")
                        .HasColumnName("pvn_number");

                    b.Property<int?>("QueueQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("queue_quantity");

                    b.Property<int?>("ReportCounter")
                        .HasColumnType("integer")
                        .HasColumnName("report_counter");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    b.Property<string>("SerialFd")
                        .HasColumnType("text")
                        .HasColumnName("serial_fd");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("started_at");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Uptime")
                        .HasColumnType("integer")
                        .HasColumnName("uptime");

                    b.Property<string>("UptimeHr")
                        .HasColumnType("text")
                        .HasColumnName("uptimehr");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.ReportStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountRecords")
                        .HasColumnType("integer")
                        .HasColumnName("countrecords");

                    b.Property<int?>("NumberReport")
                        .HasColumnType("integer")
                        .HasColumnName("numberreport");

                    b.Property<bool?>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_at");

                    b.Property<long?>("UploadedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.ToTable("reportstats", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closedat");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disconnectedat");

                    b.Property<bool?>("Errors")
                        .HasColumnType("boolean")
                        .HasColumnName("errors");

                    b.Property<string>("ErrorsDescription")
                        .HasColumnType("text")
                        .HasColumnName("errorsdescription");

                    b.Property<DateTime?>("LastReportAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastreportat");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<bool?>("ManualStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("manualstopped");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeid");

                    b.Property<int?>("QueueQty")
                        .HasColumnType("integer")
                        .HasColumnName("queueqty");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<string>("TicketStatus")
                        .HasColumnType("text")
                        .HasColumnName("ticketstatus");

                    b.Property<string>("TypeError")
                        .HasColumnType("text")
                        .HasColumnName("typeerror");

                    b.HasKey("Id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.TicketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("text")
                        .HasColumnName("performed_by");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticketid");

                    b.HasKey("Id");

                    b.ToTable("ticket_histories", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.NodeSchema", b =>
                {
                    b.HasOne("BlazorApp2.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId");

                    b.Navigation("Node");
                });
#pragma warning restore 612, 618
        }
    }
}
